# Generated by Django 4.2.7 on 2023-12-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usercheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('zipcode', models.TextField(max_length=40)),
                ('telephone', models.CharField(max_length=15)),
            ],
        ),
    ]
